# PCB footprint generated by fp-axial.pl
# Package type: AXIAL
#
# Package name: DIO-P0508_D0508
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "DIO-P0508_D0508" "D?" "" 0 0 -3000 5669 0 100 ""]
(
        Pin[-10000 0 5511 1574 5511 3543 "1" "1" "square"]
        Pin[10000 0 5511 1574 5511 3543 "2" "2" ""]
        ElementArc[10000 0 10000 10000 45 270 1000]
)

# Created with: fp-axial.pl "-d" "-v" "DIO-P0508_D0508" "05.08" "1.4" "0.9" "05.08"
