# PCB footprint generated by fp-axial.pl
# Package type: AXIAL
#
# Package name: DIO-P0330_D0330
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "DIO-P0330_D0330" "D?" "" 0 0 -3000 5669 0 100 ""]
(
        Pin[-6496 0 5511 1574 5511 3543 "1" "1" "square"]
        Pin[6496 0 5511 1574 5511 3543 "2" "2" ""]
        ElementArc[6496 0 6496 6496 45 270 1000]
)

# Created with: fp-axial.pl "-d" "-v" "DIO-P0330_D0330" "03.30" "1.4" "0.9" "03.30"
