# PCB footprint generated by fp-axial.pl
# Package type: AXIAL
#
# Package name: DIO-mM-P0432_D0432
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "DIO-mM-P0432_D0432" "D?" "" 0 0 -3000 5669 0 100 ""]
(
        Pin[-8503 0 6692 1574 6692 1574 "1" "1" "square"]
        Pin[8503 0 6692 1574 6692 1574 "2" "2" ""]
        ElementArc[8503 0 8503 8503 45 270 1000]
)

# Created with: fp-axial.pl "-m" "-M" "-d" "-v" "DIO-mM-P0432_D0432" "04.32" "1.4" "0.9" "04.32"
