# PCB footprint generated by fp-axial.pl
# Package type: AXIAL
#
# Package name: DIO-P0686_D0686
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "DIO-P0686_D0686" "D?" "" 0 0 -3000 5669 0 100 ""]
(
        Pin[-13503 0 5511 1574 5511 3543 "1" "1" "square"]
        Pin[13503 0 5511 1574 5511 3543 "2" "2" ""]
        ElementArc[13503 0 13503 13503 45 270 1000]
)

# Created with: fp-axial.pl "-d" "-v" "DIO-P0686_D0686" "06.86" "1.4" "0.9" "06.86"
