# PCB footprint generated by fp-radial.pl
# Package type: RADIAL
#
# Package name: C_250-100
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "C_250-100" "C?" "" 0 0 -3000 14999 0 100 ""]
(
        Pin[-5000 0 6763 1574 6763 5000 "1" "1" "square"]
        Pin[5000 0 6763 1574 6763 5000 "2" "2" ""]
        ElementArc[0 0 12500 12500 0 360 1000]
        ElementArc[-14500 0 500 500 0 360 1000]
)

# Created with: fp-radial.pl "-p" "C_250-100" "2.54" "1.718" "1.27" "6.35"
