# PCB footprint generated by fp-axial.pl
# Package type: AXIAL
#
# Package name: RES-mM-P0659_D0317
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "RES-mM-P0659_D0317" "R?" "" 0 0 -3000 5669 0 100 ""]
(
        Pin[-12972 0 6692 1574 6692 1574 "1" "1" ""]
        Pin[12972 0 6692 1574 6692 1574 "2" "2" ""]
        ElementArc[12972 0 6240 6240 45 270 1000]
)

# Created with: fp-axial.pl "-m" "-M" "-r" "-v" "RES-mM-P0659_D0317" "06.59" "1.4" "0.9" "03.17"
