# PCB footprint generated by fp-axial.pl
# Package type: AXIAL
#
# Package name: RES-P0254_D0254
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "RES-P0254_D0254" "R?" "" 0 0 -3000 5669 0 100 ""]
(
        Pin[-5000 0 5511 1574 5511 3543 "1" "1" ""]
        Pin[5000 0 5511 1574 5511 3543 "2" "2" ""]
        ElementArc[5000 0 5000 5000 45 270 1000]
)

# Created with: fp-axial.pl "-r" "-v" "RES-P0254_D0254" "02.54" "1.4" "0.9" "02.54"
