# PCB footprint generated by fp-axial.pl
# Package type: AXIAL
#
# Package name: RES-mM-P0254_D0254
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "RES-mM-P0254_D0254" "R?" "" 0 0 -3000 5669 0 100 ""]
(
        Pin[-5000 0 6692 1574 6692 1574 "1" "1" ""]
        Pin[5000 0 6692 1574 6692 1574 "2" "2" ""]
        ElementArc[5000 0 5000 5000 45 270 1000]
)

# Created with: fp-axial.pl "-m" "-M" "-r" "-v" "RES-mM-P0254_D0254" "02.54" "1.4" "0.9" "02.54"
