# PCB footprint generated by fp-axial.pl
# Package type: AXIAL
#
# Package name: RES-mM-P0457_D0457
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "RES-mM-P0457_D0457" "R?" "" 0 0 -3000 5669 0 100 ""]
(
        Pin[-8996 0 6692 1574 6692 1574 "1" "1" ""]
        Pin[8996 0 6692 1574 6692 1574 "2" "2" ""]
        ElementArc[8996 0 8996 8996 45 270 1000]
)

# Created with: fp-axial.pl "-m" "-M" "-r" "-v" "RES-mM-P0457_D0457" "04.57" "1.4" "0.9" "04.57"
