# PCB footprint generated by fp-axial.pl
# Package type: AXIAL
#
# Package name: RES-mM-P0762_D0508
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "RES-mM-P0762_D0508" "R?" "" 0 0 -3000 5669 0 100 ""]
(
        Pin[-15000 0 6692 1574 6692 1574 "1" "1" ""]
        Pin[15000 0 6692 1574 6692 1574 "2" "2" ""]
        ElementArc[15000 0 10000 10000 45 270 1000]
)

# Created with: fp-axial.pl "-m" "-M" "-r" "-v" "RES-mM-P0762_D0508" "07.62" "1.4" "0.9" "05.08"
