# PCB footprint generated by fp-axial.pl
# Package type: AXIAL
#
# Package name: RES-P0659_D0317
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "RES-P0659_D0317" "R?" "" 0 0 -3000 5669 0 100 ""]
(
        Pin[-12972 0 5511 1574 5511 3543 "1" "1" ""]
        Pin[12972 0 5511 1574 5511 3543 "2" "2" ""]
        ElementArc[12972 0 6240 6240 45 270 1000]
)

# Created with: fp-axial.pl "-r" "-v" "RES-P0659_D0317" "06.59" "1.4" "0.9" "03.17"
