# PCB footprint generated by fp-axial.pl
# Package type: AXIAL
#
# Package name: RES-P0508_D0508
# Aliases     : 
# Parts       : 
# Producer    : 
#
Element["" "RES-P0508_D0508" "R?" "" 0 0 -3000 5669 0 100 ""]
(
        Pin[-10000 0 5511 1574 5511 3543 "1" "1" ""]
        Pin[10000 0 5511 1574 5511 3543 "2" "2" ""]
        ElementArc[10000 0 10000 10000 45 270 1000]
)

# Created with: fp-axial.pl "-r" "-v" "RES-P0508_D0508" "05.08" "1.4" "0.9" "05.08"
